import type { Metadata } from 'next';

import '../globals.css';
import { StepProvider } from '@/contexts/StepContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function TwentyTwoLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <StepProvider>{children}</StepProvider>;
}
