import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';

import { ActiveTabProvider } from '@/contexts/ActiveTabContext';
import { Footer } from '@/components/common/footer';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ActiveTabProvider>
          <div className="lg:max-w-[1510px] md:w-[648px] sm:w-[500px] mx-auto lg:w-full relative">
            <Header />
            <div className="flex  xl:gap-[73px] gap-[50px] mx-auto justify-center ">
              <Sidebar />
              {children}
            </div>
            <Footer />
          </div>
        </ActiveTabProvider>
      </body>
    </html>
  );
}
